// packages/embed-react/src/index.tsx
import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
  type CSSProperties,
} from "react";
import {
  MontiEmbed,
  type EmbedError,
  type EmbedPosition,
  type EmbedResolveResult,
} from "@libratech/embed-core";

export type { EmbedError, EmbedPosition, EmbedResolveResult };
export { MontiEmbed };

export interface MontiEmbedProps {
  embedKey: string;
  apiBase: string;
  parentOrigin?: string;
  position?: EmbedPosition;
  agentId?: string;
  theme?: string;
  locale?: string;
  /** Controlled open state for a floating embed. */
  open?: boolean;
  /** Initial open state when `open` is uncontrolled. */
  defaultOpen?: boolean;
  inline?: boolean;
  skipResolve?: boolean;
  className?: string;
  style?: CSSProperties;
  onOpen?: () => void;
  onClose?: () => void;
  onReady?: (result?: EmbedResolveResult) => void;
  onError?: (error: EmbedError) => void;
  onDestroy?: () => void;
  onOpenChange?: (open: boolean) => void;
}

export interface MontiEmbedHandle {
  open(): void;
  close(): void;
  toggle(): void;
  destroy(): void;
  getInstance(): MontiEmbed | null;
}

export const MontiEmbedReact = forwardRef<MontiEmbedHandle, MontiEmbedProps>(
  function MontiEmbedReact(props, ref) {
    const hostRef = useRef<HTMLDivElement | null>(null);
    const embedRef = useRef<MontiEmbed | null>(null);
    const [error, setError] = useState<EmbedError | null>(null);
    const callbacks = useLatestCallbacks(props);

    const {
      embedKey,
      apiBase,
      parentOrigin,
      position = "bottom-right",
      agentId,
      theme,
      locale,
      open,
      defaultOpen = false,
      inline = false,
      skipResolve = false,
      className,
      style,
    } = props;

    useEffect(() => {
      let active = true;
      setError(null);
      const embed = new MontiEmbed({
        embedKey,
        apiBase,
        parentOrigin,
        position,
        agentId,
        theme,
        locale,
        open: open ?? defaultOpen,
        skipResolve,
        container: inline ? hostRef.current : null,
        onOpen: () => {
          callbacks.current.onOpen?.();
          callbacks.current.onOpenChange?.(true);
        },
        onClose: () => {
          callbacks.current.onClose?.();
          callbacks.current.onOpenChange?.(false);
        },
        onReady: (result) => callbacks.current.onReady?.(result),
        onError: (nextError) => {
          if (active) setError(nextError);
          callbacks.current.onError?.(nextError);
        },
        onDestroy: () => callbacks.current.onDestroy?.(),
      });
      embedRef.current = embed;
      void embed.mount();

      return () => {
        active = false;
        embed.destroy();
        if (embedRef.current === embed) embedRef.current = null;
      };
    }, [
      embedKey,
      apiBase,
      parentOrigin,
      position,
      agentId,
      theme,
      locale,
      inline,
      skipResolve,
      defaultOpen,
      callbacks,
    ]);

    useEffect(() => {
      if (open === undefined) return;
      if (open) embedRef.current?.open();
      else embedRef.current?.close();
    }, [open]);

    useImperativeHandle(
      ref,
      () => ({
        open: () => embedRef.current?.open(),
        close: () => embedRef.current?.close(),
        toggle: () => embedRef.current?.toggle(),
        destroy: () => {
          embedRef.current?.destroy();
          embedRef.current = null;
        },
        getInstance: () => embedRef.current,
      }),
      [],
    );

    const hostStyle: CSSProperties = inline
      ? { width: "100%", minHeight: 480, height: "100%", ...style }
      : { display: "contents", ...style };

    return (
      <div
        ref={hostRef}
        data-monti-embed-react="1"
        data-error={error?.code}
        className={className}
        style={hostStyle}
      />
    );
  },
);

export function useMontiEmbed(
  options: Omit<MontiEmbedProps, "className" | "style" | "inline"> & {
    container?: HTMLElement | null;
    enabled?: boolean;
  },
): {
  embed: MontiEmbed | null;
  error: EmbedError | null;
  open(): void;
  close(): void;
  toggle(): void;
} {
  const embedRef = useRef<MontiEmbed | null>(null);
  const [embed, setEmbed] = useState<MontiEmbed | null>(null);
  const [error, setError] = useState<EmbedError | null>(null);
  const callbacks = useLatestCallbacks(options);
  const enabled = options.enabled !== false;

  useEffect(() => {
    if (!enabled) {
      embedRef.current?.destroy();
      embedRef.current = null;
      setEmbed(null);
      return;
    }

    let active = true;
    setError(null);
    const instance = new MontiEmbed({
      embedKey: options.embedKey,
      apiBase: options.apiBase,
      parentOrigin: options.parentOrigin,
      position: options.position,
      agentId: options.agentId,
      theme: options.theme,
      locale: options.locale,
      open: options.open ?? options.defaultOpen,
      skipResolve: options.skipResolve,
      container: options.container ?? null,
      onOpen: () => callbacks.current.onOpen?.(),
      onClose: () => callbacks.current.onClose?.(),
      onReady: (result) => callbacks.current.onReady?.(result),
      onError: (nextError) => {
        if (active) setError(nextError);
        callbacks.current.onError?.(nextError);
      },
      onDestroy: () => callbacks.current.onDestroy?.(),
    });
    embedRef.current = instance;
    setEmbed(instance);
    void instance.mount();

    return () => {
      active = false;
      instance.destroy();
      if (embedRef.current === instance) embedRef.current = null;
      setEmbed((current) => (current === instance ? null : current));
    };
  }, [
    enabled,
    options.embedKey,
    options.apiBase,
    options.parentOrigin,
    options.position,
    options.agentId,
    options.theme,
    options.locale,
    options.skipResolve,
    options.container,
    callbacks,
  ]);

  useEffect(() => {
    if (options.open === undefined) return;
    if (options.open) embedRef.current?.open();
    else embedRef.current?.close();
  }, [options.open]);

  return {
    embed,
    error,
    open: useCallback(() => embedRef.current?.open(), []),
    close: useCallback(() => embedRef.current?.close(), []),
    toggle: useCallback(() => embedRef.current?.toggle(), []),
  };
}

function useLatestCallbacks(props: Partial<MontiEmbedProps>) {
  const callbacks = useRef({
    onOpen: props.onOpen,
    onClose: props.onClose,
    onReady: props.onReady,
    onError: props.onError,
    onDestroy: props.onDestroy,
    onOpenChange: props.onOpenChange,
  });
  callbacks.current = {
    onOpen: props.onOpen,
    onClose: props.onClose,
    onReady: props.onReady,
    onError: props.onError,
    onDestroy: props.onDestroy,
    onOpenChange: props.onOpenChange,
  };
  return callbacks;
}

export default MontiEmbedReact;

// packages/embed-web-component/src/index.ts
import {
  MontiEmbed,
  type EmbedError,
  type EmbedPosition,
  type EmbedResolveResult,
} from "@libratech/embed-core";

export type { EmbedError, EmbedPosition, EmbedResolveResult };
export { MontiEmbed };

const IDENTITY_ATTRIBUTES = [
  "embed-key",
  "api-base",
  "base-url",
  "parent-origin",
  "position",
  "agent-id",
  "theme",
  "locale",
  "inline",
  "skip-resolve",
] as const;

const OBSERVED_ATTRIBUTES = [...IDENTITY_ATTRIBUTES, "open"] as const;

const HTMLElementBase = (globalThis.HTMLElement ?? class {}) as typeof HTMLElement;

export class MontiEmbedElement extends HTMLElementBase {
  static get observedAttributes(): string[] {
    return [...OBSERVED_ATTRIBUTES];
  }

  private embed: MontiEmbed | null = null;
  private host: HTMLDivElement | null = null;
  private mountToken = 0;

  connectedCallback(): void {
    if (!this.host) {
      this.host = document.createElement("div");
      this.appendChild(this.host);
    }
    this.updateHostStyle();
    void this.remount();
  }

  disconnectedCallback(): void {
    this.teardown();
  }

  attributeChangedCallback(name: string): void {
    if (!this.isConnected) return;
    if (name === "open" && this.embed) {
      if (this.boolAttribute("open")) this.embed.open();
      else this.embed.close();
      return;
    }
    this.updateHostStyle();
    void this.remount();
  }

  open(): void {
    this.setAttribute("open", "");
    this.embed?.open();
  }

  close(): void {
    this.removeAttribute("open");
    this.embed?.close();
  }

  toggle(): void {
    if (this.hasAttribute("open")) this.close();
    else this.open();
  }

  destroy(): void {
    this.teardown();
  }

  getInstance(): MontiEmbed | null {
    return this.embed;
  }

  private teardown(): void {
    this.mountToken += 1;
    this.embed?.destroy();
    this.embed = null;
  }

  private updateHostStyle(): void {
    if (!this.host) return;
    const inline = this.boolAttribute("inline");
    this.host.style.cssText = inline
      ? "display:block;width:100%;min-height:480px;height:100%"
      : "display:contents";
  }

  private attribute(name: string): string {
    return (this.getAttribute(name) ?? "").trim();
  }

  private boolAttribute(name: string): boolean {
    if (!this.hasAttribute(name)) return false;
    return !["false", "0", "no"].includes(this.attribute(name).toLowerCase());
  }

  private async remount(): Promise<void> {
    const token = ++this.mountToken;
    this.embed?.destroy();
    this.embed = null;

    const embedKey = this.attribute("embed-key");
    const apiBase = this.attribute("api-base") || this.attribute("base-url");
    if (!embedKey || !apiBase) {
      this.dispatch("monti-error", {
        code: embedKey ? "missing_api_base" : "missing_embed_key",
        message: embedKey ? "api-base is required" : "embed-key is required",
      } satisfies EmbedError);
      return;
    }

    const embed = new MontiEmbed({
      embedKey,
      apiBase,
      parentOrigin: this.attribute("parent-origin") || undefined,
      position: (this.attribute("position") || "bottom-right") as EmbedPosition,
      agentId: this.attribute("agent-id") || undefined,
      theme: this.attribute("theme") || undefined,
      locale: this.attribute("locale") || undefined,
      open: this.boolAttribute("open"),
      skipResolve: this.boolAttribute("skip-resolve"),
      container: this.boolAttribute("inline") ? this.host : null,
      onOpen: () => {
        if (!this.hasAttribute("open")) this.setAttribute("open", "");
        this.dispatch("monti-open");
      },
      onClose: () => {
        if (this.hasAttribute("open")) this.removeAttribute("open");
        this.dispatch("monti-close");
      },
      onReady: (result) => this.dispatch("monti-ready", result),
      onError: (error) => this.dispatch("monti-error", error),
      onDestroy: () => this.dispatch("monti-destroy"),
    });
    this.embed = embed;
    await embed.mount();

    if (token !== this.mountToken || !this.isConnected) {
      embed.destroy();
      if (this.embed === embed) this.embed = null;
    }
  }

  private dispatch(name: string, detail?: unknown): void {
    this.dispatchEvent(
      new CustomEvent(name, {
        ...(detail === undefined ? {} : { detail }),
        bubbles: true,
        composed: true,
      }),
    );
  }
}

declare global {
  interface HTMLElementTagNameMap {
    "monti-embed": MontiEmbedElement;
  }
}

export function defineMontiEmbedElement(tagName = "monti-embed"): void {
  if (typeof customElements === "undefined" || customElements.get(tagName)) return;
  customElements.define(tagName, MontiEmbedElement);
}

defineMontiEmbedElement();

export default MontiEmbedElement;
